### PR TITLE
OOP school library unit tests with Rspec

### PR DESCRIPTION
**Pull request by Bria222**
# On this PR we added unit tests for the following:⬇️
<strong>
<h3>1. Book </h3>
<h3>2. Person</h3>
<h3>3. Student</h3>
<h3>4. Teacher</h3>
<h3>5. Classroom</h3>
<h3>6. Rental</h3>
<h3>7. all classes created are implementing the Decorator design pattern</h3>

</strong>

### CODE REVIEW

**Review by zhadier — CHANGES_REQUESTED** [review]
# Hi @Bria222 & @mwenyoa  👋 

Good job so far! 🌤️ 
There are some issues that you still need to work on to go to the next project but you are almost there! 🍓 



## Highlights
✔️ No linter errors
✔️ GithFlow was set up correctly
✔️ Professional pull request title and description
✔️ Amazing tests with good coverage

## Required Changes ♻️

- [ ] Great job with the tests, I really like how diverse and well-covered the tests you have done are. But one thing I kindly require of you is to add some tests for the Decorator classes aswell as it was one of the core project requirements. I'm sure you guys won't even break a sweat considering how good your testing skills are :)

image




_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question @zhadier so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Bria222** [comment]
Sure  that wont be difficult thanks @zhadier

**Comment by Bria222** [comment]
@zhadier i have implemented the changes required kindly have a look at my code thanks a lot

**Review by t-yanick — APPROVED** [review]
Hi Team, 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good job with test coverage

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Bria222** [comment]
thanks Mr  @t-yanick for  the review

**Pull request merged**
